---
# file: roles/security/tasks/fail2ban.yml

- name:  Security | fail2ban | Make sure fail2ban is installed
  apt:   pkg=fail2ban state=installed
  tags:   security

- name: Security | fail2ban | Copy the fail2ban configuration
  copy: src=fail2ban/etc_fail2ban_{{item}}.conf dest=/etc/fail2ban/{{item}}.conf owner=root group=root mode=0644
  with_items:
  - fail2ban
  - jail
  notify: restart fail2ban
