---
# file: roles/timezone/tasks/main.yml

- name:       Timezone | Make sure the dependencies are installed
  apt:        name={{ item }} state=installed
  with_items:
    - tzdata
    - ntp
  tags:       time

- name:       Timezone | Configure the ntp servers (/etc/ntp.conf)
  template:   src=ntp.conf.j2 dest=/etc/ntp.conf owner=root group=root mode=0644
  notify:     restart ntpd
  tags:       time

- name:       Timezone | Make sure ntpd is running and enabled
  service:    name=ntp state=restarted enabled=yes
  tags:       time

- name:       Timezone | Add timezone to /etc/timezone
  copy:       content={{ timezone }} dest=/etc/timezone owner=root group=root mode=0644
  notify:     [update timezone, restart cron]
  tags:       time
